name: Continuous Integration
on: 
  push:
    branches:
      - master
  pull_request:                      

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest     
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      - name: Build C# project
        run: dotnet build
      - name: Run C# tests
        run: dotnet test
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name : Install ts dependency
        run: npm install
        working-directory: ./DotnetTemplate.Web
      - name: Build TS project
        run: npm run build
        working-directory: ./DotnetTemplate.Web
      - name: Run TS tests
        run: npm t
        working-directory: ./DotnetTemplate.Web
      - name: Run TS linter
        run: npm run lint
        working-directory: ./DotnetTemplate.Web